# Generated by Django 4.1.2 on 2022-10-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('BF', 'Завтрак'), ('LN', 'Обед'), ('DN', 'Ужин'), ('DS', 'Десерт')], db_index=True, default='DN', max_length=2, verbose_name='Период приёма пищи')),
            ],
            options={
                'verbose_name': 'Период приёма пищи',
                'verbose_name_plural': 'Период приёма пищи',
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='period',
        ),
    ]
