# Generated by Django 4.1.2 on 2022-10-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_period_remove_recipe_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='period',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.period', verbose_name='Период приема пищи'),
        ),
    ]
