# Generated by Django 4.1.2 on 2022-10-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_foodcategory_title_alter_period_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ('pk',), 'verbose_name': 'Категория Еды', 'verbose_name_plural': 'Категории Еды'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ('pk',), 'verbose_name': 'Период приёма пищи', 'verbose_name_plural': 'Период приёма пищи'},
        ),
    ]
