# Generated by Django 4.1.2 on 2022-10-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_foodcategory_options_alter_period_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(max_length=100, verbose_name='Период приёма пищи'),
        ),
    ]
