# Generated by Django 4.1.2 on 2022-10-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_period_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
