# Generated by Django 4.0.1 on 2022-10-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_foodcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='period',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.Period', verbose_name='Период приема пищи'),
        ),
    ]
