# Generated by Django 4.1.2 on 2022-10-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория Аллергии',
                'verbose_name_plural': 'Категории Аллергий',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allergy_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='recipes.allergycategory', verbose_name='Аллергии'),
        ),
    ]
