# Generated by Django 4.1.2 on 2022-10-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_allergycategory_ingredient_allergy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergy_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes', to='recipes.allergycategory'),
        ),
    ]
