# Generated by Django 4.1.2 on 2022-10-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0009_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('OM', '1 месяц'), ('TM', '3 месяца'), ('SM', '6 месяцев'), ('WM', '12 месяцев')], db_index=True, default='OM', max_length=2, verbose_name='Срок заказа')),
                ('breakfast', models.BooleanField(default=True, verbose_name='Завтраки')),
                ('lunch', models.BooleanField(default=True, verbose_name='Обеды')),
                ('dinner', models.BooleanField(default=True, verbose_name='Ужины')),
                ('dessert', models.BooleanField(default=True, verbose_name='Десерты')),
                ('amount_person', models.PositiveIntegerField(default=1, verbose_name='Количество персон')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='recipes.foodcategory', verbose_name='Категория')),
            ],
        ),
    ]
