# Generated by Django 4.1.2 on 2022-10-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipeingredient_amount'),
        ('order', '0003_alter_promocode_options_order_user_alter_order_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_form_cost',
            field=models.PositiveIntegerField(default=100, verbose_name='Цена сета для юзера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='recipes.foodcategory', verbose_name='Категория'),
        ),
    ]
