# Generated by Django 4.1.2 on 2022-10-08 16:35

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipeingredient_amount'),
        ('order', '0005_order_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, default=order.models.get_default_category, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='recipes.foodcategory', verbose_name='Категория'),
        ),
    ]
