# Generated by Django 4.1.2 on 2022-10-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_options_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.PositiveIntegerField(default=1, verbose_name='Срок заказа в месяцах'),
        ),
    ]
