# Generated by Django 4.1.2 on 2022-10-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_daymenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daymenu',
            options={'verbose_name': ('Меню на день',), 'verbose_name_plural': 'Меню на день'},
        ),
    ]
