# Generated by Django 4.1.2 on 2022-10-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipeingredient_amount'),
        ('order', '0009_alter_daymenu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='orders', to='recipes.ingredient', verbose_name='Аллергии'),
        ),
    ]
