# Generated by Django 4.1.2 on 2022-10-10 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория Аллергии',
                'verbose_name_plural': 'Категории Аллергий',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='allergies',
        ),
        migrations.AddField(
            model_name='order',
            name='allergies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.allergycategory', verbose_name='Аллергии'),
        ),
    ]
