# Generated by Django 4.1.2 on 2022-10-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_allergycategory_ingredient_allergy_category'),
        ('order', '0011_allergycategory_remove_order_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='allergies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='recipes.allergycategory', verbose_name='Аллергии'),
        ),
        migrations.DeleteModel(
            name='AllergyCategory',
        ),
    ]
