# Generated by Django 4.1.2 on 2022-10-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_allergy_categories'),
        ('order', '0012_alter_order_allergies_delete_allergycategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='allergies',
        ),
        migrations.AddField(
            model_name='order',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='recipes.allergycategory', verbose_name='Аллергии'),
        ),
    ]
